package Server.Enums;

public enum EventType {
    PLAYERCOLOR, // QUANDO IL CLIENT LA RICEVE INDICA SE IL COLORE VA BENE O NO
    UNAVAILABLECOLORS,
    PLAYERSORDER,
    PLAYERNAME, // QUANDO IL CLIENT LA RICEVE INDICA SE IL SUO NOME VA BENE O NO
    NEWPLAYER, // CONTIENE IL NOME DELL'ALTRO PLAYER
    SECRETCARDSELECTION,
    OTHERSSECRETCARD,
    STARTINGCARD,
    OTHERSSTARTINGCARD,
    DRAWCARD,
    OTHERSDRAWCARD,
    TIMEOUT,
    NEXTTURN,
    CARDPLACEMENT,
    OTHERSCARDPLACEMENT,
    ENDGAMEPHASE,
    LEADERBOARD,
    GAMEOVER,
    NEWMESSAGE, // CHAT
    RECONNECTION,
    OHTERRECONECTION,
    READYSTATUS, // SI USA ANCHE AL CONTRARIO, E INDICA LA LISTA DEI GIOCATORI PRONTI
    BOARDINIT,
    NEWPOINTS,
    OTHERSNEWPOINTS,
    NEWSYMBOLS,
    QUITORPLAYAGAIN,
    MATCHALREADYFULL,





}
