package Server.Enums;

public enum MessageType {
    BOARDINIT,
    CARDPLACEMENT,
    CHAT,
    DRAWCARD,
    ENDGAMEPHASE,
    INITIALHAND,
    LEADERBOARD,
    MATCHALREADYFULL,
    NEWPLAYER,
    NEWPOINTS,
    NEWSYMBOLS,
    NEXTTURN,
    OTHERCARDPLACEMENT,
    OTHERDRAWCARD,
    OTHERNEWPOINTS,
    OTHERRECONNECTION,
    OTHERSECRETCARD,
    OTHERSTARTINGCARD,
    PLAYERCOLOR,
    PLAYERNAME,
    PLAYERSORDER,
    QUITORPLAYAGAIN,
    READYSTATUS,
    RECONNECTION,
    SECRETCARDS,
    TIMEOUTMESSAGE,
    UNAVAIABLECOLORS,
    STARTINGCARDS

}
