package main.java.Enums;

public enum EventType {
    SET_COLOR,
    PLAYERSORDER,
    PLAYERSDATA,
    SECRETCARDSELECTION,
    OTHERSSECRETCARDSELECTION,
    STARTINGCARDS,
    OTHERSSTARTINGCARDS,
    DRAWCARD,
    TIMEOUT,
    NEXTTURN,
    CARDPLACEMENT,
    ENDGAMEPHASE,
    LEADERBOARD,
    GAMEOVER,
    NEWMESSAGE,
    RECONNECTION

}
