package main.java.Enums;

public enum Symbol {
    ANIMAL, FUNGUS, PLANT, BUG,
    QUILL, BOTTLE, PARCHMENT,
    EMPTY, NONE, COVERED_CORNER,
    PATTERN1, PATTERN2, PATTERN3, PATTERN4, PATTERN5, PATTERN6, PATTERN7, PATTERN8


}
